#!/usr/bin/env python3
"""Plot RSSI logs generated by uart_rssi_logger.py.

It supports the current CSV schema:
- timestamp_iso
- elapsed_s
- rssi_dbm
- distance_cm
- event
- raw_line
"""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from statistics import mean, pstdev
from typing import Iterable


@dataclass
class Sample:
    elapsed_s: float
    rssi_dbm: int
    distance_cm: int


@dataclass
class Event:
    elapsed_s: float
    distance_cm: int
    event: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plot RSSI CSV data.")
    parser.add_argument("csv_path", help="CSV file generated by uart_rssi_logger.py")
    parser.add_argument(
        "--output",
        help="Output PNG path. Default: same name as CSV with .png extension",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Show the plot window after saving",
    )
    parser.add_argument(
        "--title",
        default="RSSI log",
        help="Plot title",
    )
    parser.add_argument(
        "--step-cm",
        type=int,
        help="Distance step for x-axis ticks. If omitted, it is auto-detected.",
    )
    return parser.parse_args()


def read_csv(csv_path: Path) -> tuple[list[Sample], list[Event]]:
    samples: list[Sample] = []
    events: list[Event] = []

    with open(csv_path, "r", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            elapsed_raw = (row.get("elapsed_s") or "").strip()
            rssi_raw = (row.get("rssi_dbm") or "").strip()
            distance_raw = (row.get("distance_cm") or "").strip()
            event_raw = (row.get("event") or "").strip()

            if not elapsed_raw:
                continue

            try:
                elapsed_s = float(elapsed_raw)
            except ValueError:
                continue

            if event_raw:
                try:
                    distance_cm = int(distance_raw) if distance_raw else 0
                except ValueError:
                    distance_cm = 0
                events.append(Event(elapsed_s=elapsed_s, distance_cm=distance_cm, event=event_raw))
                continue

            if not rssi_raw:
                continue

            try:
                samples.append(
                    Sample(
                        elapsed_s=elapsed_s,
                        rssi_dbm=int(rssi_raw),
                        distance_cm=int(distance_raw) if distance_raw else 0,
                    )
                )
            except ValueError:
                continue

    return samples, events


def build_segments(events: Iterable[Event], last_time: float) -> list[tuple[float, float, int]]:
    ordered = sorted(events, key=lambda e: e.elapsed_s)
    segments: list[tuple[float, float, int]] = []

    current_distance = None
    segment_start = 0.0

    for event in ordered:
        if event.event in {"start_distance"} or event.event.startswith("distance_"):
            if current_distance is not None:
                segments.append((segment_start, event.elapsed_s, current_distance))
            current_distance = event.distance_cm
            segment_start = event.elapsed_s

    if current_distance is not None:
        segments.append((segment_start, last_time, current_distance))

    return segments


def distance_stats(samples: list[Sample]) -> list[tuple[int, int, float, float]]:
    grouped: dict[int, list[int]] = defaultdict(list)
    for sample in samples:
        grouped[sample.distance_cm].append(sample.rssi_dbm)

    result: list[tuple[int, int, float, float]] = []
    for distance_cm in sorted(grouped):
        values = grouped[distance_cm]
        avg = mean(values)
        spread = pstdev(values) if len(values) > 1 else 0.0
        result.append((distance_cm, len(values), avg, spread))
    return result


def rebase_time_to_first_sample(
    samples: list[Sample], events: list[Event]
) -> tuple[list[Sample], list[Event]]:
    if not samples:
        return samples, events

    t0 = min(sample.elapsed_s for sample in samples)
    shifted_samples = [
        Sample(
            elapsed_s=sample.elapsed_s - t0,
            rssi_dbm=sample.rssi_dbm,
            distance_cm=sample.distance_cm,
        )
        for sample in samples
    ]
    shifted_events = [
        Event(
            elapsed_s=event.elapsed_s - t0,
            distance_cm=event.distance_cm,
            event=event.event,
        )
        for event in events
    ]
    return shifted_samples, shifted_events


def infer_step_cm(events: list[Event], samples: list[Sample]) -> int:
    # Prefer explicit distance change events like distance_plus_20cm.
    steps_from_events: list[int] = []
    for event in events:
        if not event.event.startswith("distance_plus_"):
            continue
        suffix = event.event.removeprefix("distance_plus_").removesuffix("cm")
        try:
            step = int(suffix)
            if step > 0:
                steps_from_events.append(step)
        except ValueError:
            continue

    if steps_from_events:
        return steps_from_events[0]

    unique_distances = sorted({sample.distance_cm for sample in samples})
    deltas = [
        curr - prev
        for prev, curr in zip(unique_distances, unique_distances[1:])
        if (curr - prev) > 0
    ]
    if deltas:
        return min(deltas)

    return 20


def build_distance_ticks(max_distance_cm: int, step_cm: int) -> list[int]:
    ticks = [0, 10]
    value = 10 + step_cm
    while value <= max_distance_cm:
        ticks.append(value)
        value += step_cm

    unique_sorted_ticks = sorted({tick for tick in ticks if tick <= max_distance_cm})
    if max_distance_cm not in unique_sorted_ticks:
        unique_sorted_ticks.append(max_distance_cm)
    return unique_sorted_ticks


def main() -> int:
    args = parse_args()
    csv_path = Path(args.csv_path)
    if not csv_path.exists():
        print(f"[ERROR] CSV not found: {csv_path}")
        return 1

    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("[ERROR] matplotlib is required. Install it with: pip install matplotlib")
        return 1

    samples, events = read_csv(csv_path)
    if not samples:
        print("[ERROR] No RSSI samples found in CSV.")
        return 1

    samples, events = rebase_time_to_first_sample(samples, events)

    output_base = Path(args.output) if args.output else csv_path.with_suffix(".png")

    elapsed = [s.elapsed_s for s in samples]
    rssi = [s.rssi_dbm for s in samples]
    distances = [s.distance_cm for s in samples]
    segments = build_segments(events, last_time=max(elapsed))
    stats = distance_stats(samples)
    step_cm = args.step_cm if args.step_cm and args.step_cm > 0 else infer_step_cm(events, samples)
    max_distance_cm = max(distances)
    distance_ticks = build_distance_ticks(max_distance_cm, step_cm)

    time_plot_path = output_base.with_name(f"{output_base.stem}_time.png")
    distance_plot_path = output_base.with_name(f"{output_base.stem}_distance.png")

    fig_time, ax_time = plt.subplots(1, 1, figsize=(12, 5.5), constrained_layout=True)

    ax_time.plot(elapsed, rssi, color="#005f73", linewidth=1.2, label="RSSI")
    ax_time.set_title(args.title)
    ax_time.set_xlabel("Elapsed time (s)")
    ax_time.set_ylabel("RSSI (dBm)")
    ax_time.grid(True, linestyle="--", alpha=0.3)

    if segments:
        y_min = min(rssi)
        y_max = max(rssi)
        palette = ["#e9d8a6", "#94d2bd", "#cde4f0", "#f8c9b0", "#d7c0f1"]
        for idx, (start, end, distance_cm) in enumerate(segments):
            ax_time.axvspan(start, end, color=palette[idx % len(palette)], alpha=0.18)
            ax_time.text(
                (start + end) / 2,
                y_max,
                f"{distance_cm} cm",
                ha="center",
                va="bottom",
                fontsize=9,
                rotation=0,
                bbox=dict(boxstyle="round,pad=0.2", facecolor="white", edgecolor="none", alpha=0.7),
            )
        ax_time.set_ylim(y_min - 2, y_max + 4)

    for event in events:
        if event.event.startswith("distance_") or event.event == "start_distance":
            ax_time.axvline(event.elapsed_s, color="#bb3e03", linestyle="--", linewidth=1, alpha=0.6)

    ax_time.legend(loc="best")
    fig_time.savefig(time_plot_path, dpi=160)
    print(f"[INFO] Saved time plot to {time_plot_path}")

    fig_dist, ax_dist = plt.subplots(1, 1, figsize=(12, 5.5), constrained_layout=True)
    ax_dist.scatter(distances, rssi, s=12, alpha=0.7, color="#0a9396", edgecolors="none")
    ax_dist.set_title("RSSI vs Distance")
    ax_dist.set_xlabel("Distance (cm)")
    ax_dist.set_ylabel("RSSI (dBm)")
    ax_dist.grid(True, linestyle="--", alpha=0.3)
    ax_dist.set_xticks(distance_ticks)
    ax_dist.set_xticklabels([f"{tick}cm" for tick in distance_ticks])

    for distance_cm, count, avg, spread in stats:
        ax_dist.errorbar(distance_cm, avg, yerr=spread, fmt="o", color="#ae2012", capsize=4)
        ax_dist.annotate(
            f"{distance_cm} cm\n n={count}\n μ={avg:.1f}",
            (distance_cm, avg),
            textcoords="offset points",
            xytext=(6, 6),
            fontsize=8,
        )

    fig_dist.savefig(distance_plot_path, dpi=160)
    print(f"[INFO] Saved distance plot to {distance_plot_path}")

    print("\nDistance summary:")
    print("distance_cm,samples,mean_rssi,std_rssi")
    for distance_cm, count, avg, spread in stats:
        print(f"{distance_cm},{count},{avg:.2f},{spread:.2f}")

    if args.show:
        plt.show()
    else:
        plt.close(fig_time)
        plt.close(fig_dist)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
