#!/usr/bin/env python3
"""Read RSSI values from UART and store them in a CSV file.

Expected UART lines include patterns such as:
- RSSI: -65
- Muestra RSSI: -65
"""

import argparse
import csv
from pathlib import Path
import re
import sys
import time
from datetime import datetime

import serial

try:
    import msvcrt  # Windows-only non-blocking keyboard polling
except ImportError:
    msvcrt = None

RSSI_REGEX = re.compile(r"(?:^|\s)(?:RSSI|Muestra RSSI)\s*:\s*(-?\d+)")


def build_output_name() -> str:
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_dir = Path(__file__).resolve().parent / "rssi_logger"
    output_dir.mkdir(parents=True, exist_ok=True)
    return str(output_dir / f"rssi_log_{stamp}.csv")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Listen UART, extract RSSI and save to CSV."
    )
    parser.add_argument("--port", required=True, help="Serial port (e.g. COM5)")
    parser.add_argument("--baud", type=int, default=115200, help="Baudrate")
    parser.add_argument(
        "--output",
        default=build_output_name(),
        help="CSV output path (default: autogenerated)",
    )
    parser.add_argument(
        "--timeout", type=float, default=1.0, help="Serial timeout in seconds"
    )
    parser.add_argument(
        "--initial-distance-cm",
        type=int,
        default=10,
        help="Initial distance in cm",
    )
    parser.add_argument(
        "--step-cm",
        type=int,
        default=50,
        help="Distance change step for '+' and '-' keys",
    )
    parser.add_argument(
        "--plot",
        action="store_true",
        help="Generate a PNG plot with distance annotations when logging ends",
    )
    return parser.parse_args()


def write_event_row(
    writer: csv.writer,
    csv_file,
    start: float,
    distance_cm: int,
    event: str,
    raw_line: str = "",
) -> None:
    now = datetime.now().isoformat(timespec="milliseconds")
    elapsed = time.time() - start
    writer.writerow([now, f"{elapsed:.3f}", "", distance_cm, event, raw_line])
    csv_file.flush()
    print(f"{now} EVENT={event} distance={distance_cm} cm")


def poll_keyboard(
    writer: csv.writer,
    csv_file,
    start: float,
    distance_cm: int,
    step_cm: int,
) -> tuple[int, bool]:
    if msvcrt is None:
        return distance_cm, False

    stop_requested = False
    while msvcrt.kbhit():
        key = msvcrt.getwch()

        if key in ("+", "="):
            distance_cm += step_cm
            write_event_row(writer, csv_file, start, distance_cm, f"distance_plus_{step_cm}cm")
        elif key == "-":
            distance_cm = max(0, distance_cm - step_cm)
            write_event_row(writer, csv_file, start, distance_cm, f"distance_minus_{step_cm}cm")
        elif key.lower() == "m":
            write_event_row(writer, csv_file, start, distance_cm, "marker")
        elif key.lower() == "q":
            write_event_row(writer, csv_file, start, distance_cm, "stop_by_key")
            stop_requested = True

    return distance_cm, stop_requested


def generate_plot(csv_path: Path) -> None:
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("[WARN] matplotlib is not installed. Install with: pip install matplotlib")
        return

    elapsed_values = []
    rssi_values = []
    distance_values = []
    events = []

    with open(csv_path, "r", newline="", encoding="utf-8") as csv_file:
        reader = csv.DictReader(csv_file)
        for row in reader:
            elapsed = row.get("elapsed_s", "").strip()
            rssi = row.get("rssi_dbm", "").strip()
            distance = row.get("distance_cm", "").strip()
            event = row.get("event", "").strip()

            if event:
                try:
                    events.append((float(elapsed), distance, event))
                except ValueError:
                    pass

            if not elapsed or not rssi:
                continue

            try:
                elapsed_values.append(float(elapsed))
                rssi_values.append(int(rssi))
                distance_values.append(distance)
            except ValueError:
                continue

    if not elapsed_values:
        print("[WARN] No RSSI samples to plot.")
        return

    fig, ax = plt.subplots(figsize=(11, 5.5))
    ax.plot(elapsed_values, rssi_values, linewidth=1.3, color="#005f73")
    ax.set_title("RSSI vs Time")
    ax.set_xlabel("Elapsed time (s)")
    ax.set_ylabel("RSSI (dBm)")
    ax.grid(True, linestyle="--", alpha=0.35)

    y_top = max(rssi_values)
    for ev_time, ev_distance, ev_name in events:
        if not ev_name.startswith("distance_"):
            continue
        ax.axvline(ev_time, color="#bb3e03", linestyle="--", alpha=0.6, linewidth=1)
        label = f"{ev_distance} cm"
        ax.text(ev_time, y_top, label, rotation=90, va="bottom", ha="right", fontsize=8)

    plot_path = csv_path.with_suffix(".png")
    fig.tight_layout()
    fig.savefig(plot_path, dpi=150)
    plt.close(fig)
    print(f"[INFO] Plot saved to: {plot_path}")


def main() -> int:
    args = parse_args()
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        ser = serial.Serial(args.port, args.baud, timeout=args.timeout)
    except serial.SerialException as exc:
        print(f"[ERROR] Could not open serial port {args.port}: {exc}")
        return 1

    start = time.time()
    distance_cm = args.initial_distance_cm

    print(f"[INFO] Listening on {args.port} @ {args.baud} baud")
    print(f"[INFO] Writing CSV to: {output_path}")
    print("[INFO] Keys: '+' increase distance, '-' decrease distance, 'm' marker, 'q' stop")
    print(f"[INFO] Start distance: {distance_cm} cm | Step: {args.step_cm} cm")
    print("[INFO] Press Ctrl+C to stop")

    with ser, open(output_path, "w", newline="", encoding="utf-8") as csv_file:
        writer = csv.writer(csv_file)
        writer.writerow(
            ["timestamp_iso", "elapsed_s", "rssi_dbm", "distance_cm", "event", "raw_line"]
        )
        write_event_row(writer, csv_file, start, distance_cm, "start_distance")

        try:
            while True:
                distance_cm, stop_requested = poll_keyboard(
                    writer, csv_file, start, distance_cm, args.step_cm
                )
                if stop_requested:
                    break

                raw = ser.readline()
                if not raw:
                    continue

                line = raw.decode("utf-8", errors="ignore").strip()
                if not line:
                    continue

                match = RSSI_REGEX.search(line)
                if match is None:
                    continue

                rssi = int(match.group(1))
                now = datetime.now().isoformat(timespec="milliseconds")
                elapsed = time.time() - start

                writer.writerow([now, f"{elapsed:.3f}", rssi, distance_cm, "", line])
                csv_file.flush()

                print(f"{now} RSSI={rssi} dBm distance={distance_cm} cm")

        except KeyboardInterrupt:
            print("\n[INFO] Logging stopped by user.")

    if args.plot:
        generate_plot(output_path)

    return 0


if __name__ == "__main__":
    sys.exit(main())
